
# You can use this file to easily send requests to your API.
# Prerequisite: humao.rest-client Vscode plugin (already present on codespace)
# High-level overview of REST API concepts used here: https://www.packtpub.com/en-us/learning/how-to-tutorials/what-are-rest-verbs-and-status-codes-tutorial?srsltid=AfmBOoppDqtkhRxj5BLZONRZFzRDmh6eP-xyTo6H4OuEHYuVbrg1d4Dm


# Requests for API endpoints of the sample project:

### Hello world endpoint: get response "Hello, Stranger!"
GET http://localhost:8080/hello-world

### Hello world with a request param passed.
# When sending the request it will ask you for the name
# hitting enter will avoid passing the param, and do the default behaviour above
# @prompt name The name to display in response
GET http://localhost:8080/hello-world
    ?name={{name}}

### Save a greeting to database
@postGreetingId = 1001
@postGreetingContent = Hello!
POST http://localhost:8080/greetings
Content-Type: application/json

{
    "id": "{{postGreetingId}}",
    "content": "{{postGreetingContent}}"
}

### Get all greetings
GET http://localhost:8080/greetings

### Get info for greeting with given content
# @prompt content Greeting content to look for, defaults to "Overview"
GET http://localhost:8080/info
    ?title={{content}}

### Update an existing greeting
@putGreetingId = 1001
@putGreetingContent = Hello again!
PUT http://localhost:8080/greetings/{{putGreetingId}}
Content-Type: application/json

{
    "content": "{{putGreetingContent}}"
}

### Delete greeting
@deleteGreetingId = 1001
DELETE http://localhost:8080/greetings/{{deleteGreetingId}}


# TODO add requests for your own endpoints!

### Get all furniture
GET http://localhost:8080/furniture
Accept: application/json

### Get furniture by SKU
GET http://localhost:8080/furniture/DRAWER-187
Accept: application/json

### Create new furniture
POST http://localhost:8080/furniture
Content-Type: application/json

{
  "name": "Drawer 187",
  "sku": "DRAWER-187",
  "categoryCode": 6,
  "price": 49,
  "stockQuantity": 20,
  "material": "Wood",
  "description": "A stylish wooden drawer.",
  "supplierId": "67d0589a2111277a16dfee90"
}

### Update furniture by SKU
PUT http://localhost:8080/furniture/DRAWER-187
Content-Type: application/json

{
  "name": "Drawer 187",
  "sku": "DRAWER-187",
  "categoryCode": 6,
  "price": 48,
  "stockQuantity": 20,
  "material": "Wood",
  "description": "A stylish wooden chair.",
  "supplierId": "67d0589a2111277a16dfee90"
}

### Delete furniture by SKU
DELETE http://localhost:8080/furniture/DRAWER-187

### Delete all furniture
DELETE http://localhost:8080/furniture

### Get all categories
GET http://localhost:8080/categories
Accept: application/json

### Get category by code
GET http://localhost:8080/categories/6
Accept: application/json

### Create new category
POST http://localhost:8080/categories
Content-Type: application/json

{
  "categoryCode": 6,
  "name": "Drawer"
}

### Update category by code
PUT http://localhost:8080/categories/6
Content-Type: application/json

{
  "categoryCode": 6,
  "name": "Drawer"
}

### Delete category by code
DELETE http://localhost:8080/categories/6

### Delete all categories
DELETE http://localhost:8080/categories

### Create new supplier
POST http://localhost:8080/suppliers
Content-Type: application/json

{
  "name": "Supplier 1",
  "email": "supplier1@gmail.com",
  "phone": "123-456-0000",
  "address": "1234 Supplier St, Supplier City, Supplier Country"
}

### Get all suppliers
GET http://localhost:8080/suppliers
Accept: application/json

### Update supplier
PUT http://localhost:8080/suppliers/67d971fea20f8e792cb190fa
Content-Type: application/json

{
  "name": "Supplier 113",
  "email": "supplier113@gmail.com"
}

### Get supplier by name
GET http://localhost:8080/suppliers/Supplier%20113
Accept: application/json

### Delete supplier by ID
DELETE http://localhost:8080/suppliers/67d8611e0be2aa4fb9abff7c
Accept: application/json

### Delete all suppliers
DELETE http://localhost:8080/suppliers
Accept: application/json

### Create user
POST http://localhost:8080/users
Content-Type: application/json

{
	"name": "Johny Test",
	"email": "email@gmail.com",
	"phone": "0712312312",
	"role": "User"
}
###


### Get all users
GET http://localhost:8080/users

###

### Update user
POST http://localhost:8080/users
Content-Type: application/json

{
	"name": "Johny Test",
	"email": "email@gmail.com",
	"phone": "0712312312",
	"role": "User"
}
###

### Delete user by id
DELETE http://localhost:8080/users/67d0619865c5414ab575cb1e

### Get user by id
GET http://localhost:8080/users/{id}

### delete all users
DELETE http://localhost:8080/users

