{
 "title": "Hello App Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Login duration rate[1m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(auth_login_duration_seconds_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "auth login attempts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "auth_login_attempts_total" }
   ]
  },
  {
   "title": "auth login failed validations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "auth_login_failed_validation_total"
    }
   ]
  },
  {
   "title": "total register attempts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    { "expr": "auth_register_attempts_total" }
   ]
  },
  {
   "title": "auth_register_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "auth_register_duration_seconds_count"
    }
   ]
  },
  {
   "title": "get hello time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    { "expr": "hello_info_time_seconds_max" }
   ]
  },
  {
   "title": "spring_data_repository_invocations_seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_max"
    }
   ]
  },
  {
   "title": "spring_data_repository_invocations_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_count"
    }
   ]
  },
  {
   "title": "spring_data_repository_invocations_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_count"
    }
   ]
  }
 ]
}